package com.juanzurita.framework.remote

object ApiConstants {

    const val API_FORMAT = "json"
    const val DEVICE = "android"
    const val API_KEY = "b3fcd6725e03f4e5d588f6624cac5522"
    const val LIVE_MATCHES_REFRESH_TIME: Long = 10000
    const val APP_SITE = "ResultadosAndroid"

    object BaseUrl {
        const val DEBUG = "https://devapp.besoccer.com"
        const val PRODUCTION = "https://fast.besoccer.com"
    }

    object Params {
        const val KEY = "key"
        const val FORMAT = "format"
        const val TZ = "tz"
        const val LANG = "lang"
        const val ISOCODE = "isocode"
        const val SITE = "site"
        const val V = "v"
        const val VR = "vr"
        const val REQ = "req"
        const val ID = "id"
        const val OPTION = "option"
        const val YEAR = "year"
        const val CATEGORY = "category"
        const val TOKEN = "token"
        const val TYPE = "type"
        const val USER = "user"
        const val USER_ID = "userId"
        const val TEAM = "team"
        const val T1 = "t1"
        const val T2 = "t2"
        const val T4 = "t4"
        const val DT1 = "dt1"
        const val DT2 = "dt2"
        const val INIT = "init"
        const val LIMIT = "limit"
        const val ZONE = "zone"
        const val MATCH_ID = "matchId"
        const val MATCH = "match"
        const val LEAGUE = "league"
        const val ROUND = "round"
        const val GROUP = "group"
        const val TEAMS = "teams"
        const val COMPETITIONS = "competitions"
        const val PLAYERS = "players"
        const val EXTRA = "extra"
        const val VALUE = "value"
        const val HASH = "hash"
        const val ACTION = "action"
        const val EXTENDED = "extended"
        const val FILTER = "filter"
        const val ALERTS = "alerts"
        const val TWOLEGGED = "twolegged"
        const val COMMENT = "comment"
        const val LAST_COMMENT = "last_comment"
        const val COMMENT_ID = "comment_id"
        const val TOP = "top"
        const val DEVICE_NAME = "device"
        const val PEN = "pen"
        const val DATE = "date"
        const val UPDATED = "updated"
        const val R1 = "r1"
        const val R2 = "r2"
        const val P1 = "p1"
        const val P2 = "p2"
        const val C1 = "C1"
        const val C2 = "C2"
        const val Y1 = "Y1"
        const val Y2 = "Y2"
        const val PAGE = "page"
        const val MATCHES = "matches"
        const val QUERY = "q"
        const val COUNTRY = "country"
        const val OFFSET = "extra"
        const val LOCALE = "locale"
        const val USERS = "users"
        const val NAME = "name"
        const val SURNAME = "surname"
        const val GENDER = "gender"
        const val BIRTHDAY = "birthday"
        const val MESSAGE_ID = "message_id"
        const val EMAIL = "email"
        const val MESSAGE = "message"
        const val MESSAGE_SUBJECT = "message_subject"
        const val FB_UID = "fb_uid"
        const val FB_DATA = "fb_data"
        const val PASSWORD = "password"
        const val IS_FAVORITES = "isFavorites"
        const val PLAY = "play"
        const val ORDER = "order"
        const val TIME = "time"
        const val ALIAS = "alias"
        const val ID_1 = "id_1"
        const val ID_2 = "id_2"
        const val UUID = "uuid"
        const val UPDATE = "updated"
        const val SO_VERSION = "version_os"
        const val APP_VERSION = "version_app"
        const val TOKEN_OLD = "token_old"
        const val MARKET = "market"
        const val PAGE_LIMIT = "page_limit"
        const val START = "start_from"
    }

    object Paths {
        const val MATCHS_DAY = "matchsday_watch_v2"
        const val MATCH_DETAIL = "match_detail_watch_v2"
        const val LIVE_RESULTS = "live_results"
        const val MATCH_EVENTS = "match_events_watch_v2"
        const val MATCH_LINEUPS = "match_lineups_watch_v2"
        const val MATCH_TABLE = "competition_tables_watch_v2"
    }
}